USE [ADMINISTRATION]
GO
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'BPD', N'BPD', N'Business Premium Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'CIR', N'CIR', N'Cirrus®')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DAG', N'DAG', N'Gold Debit MasterCard® Salary')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DAP', N'DAP', N'Platinum Debit MasterCard® Salary')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DAS', N'DAS', N'Standard Debit MasterCard® Salary')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DLG', N'DLG', N'Debit MasterCard® Gold - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DLH', N'DLH', N'Debit MasterCard® World Embossed - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DLI', N'DLS', N'Debit MasterCard® Standard Student Card - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DLP', N'DLP', N'Debit MasterCard® Platinum - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DLS', N'DLS', N'Debit MasterCard® Card - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DLU', N'DLS', N'Debit MasterCard® Unembossed - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'DOS', N'DOS', N'Standard Debit MasterCard® Social')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MAB', N'MAB', N'World Elite™ MasterCard® for Business Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MAC', N'MAC', N'MasterCard® World Elite™ Corporate Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MAP', N'MAP', N'MAP - MasterCard Commercial Payments Account')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MAQ', N'MAQ', N'MasterCard® Prepaid Commercial Payments Account')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MBB', N'MBB', N'MasterCard Prepaid Consumer')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MBC', N'MBC', N'MasterCard Prepaid Voucher')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MBD', N'MBD', N'MasterCard® Professional Debit BusinessCard')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MBE', N'MBE', N'MasterCard® Electronic™ Business Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MBK', N'MBK', N'MasterCard Black® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MBP', N'MBP', N'MasterCard Corporate Prepaid')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MBS', N'MBS', N'MasterCard® B2B Product MasterCard Corporate Prepaid Travel')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MBW', N'MBW', N'World MasterCard® Black Edition - Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCA', N'MCE', N'MasterCard® Electronic™ Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCB', N'MCB', N'MasterCard® BusinessCard Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCC', N'MCC', N'MasterCard® Credit Card (mixed BIN)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCD', N'MCD', N'Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCE', N'MCE', N'MasterCard® Electronic™ Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCF', N'MCF', N'MasterCard® Fleet Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCG', N'MCG', N'Gold MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCH', N'MCH', N'MasterCard® Premium Charge')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCM', N'MCO', N'MasterCard® Corporate Meeting Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCO', N'MCO', N'MasterCard® Corporate Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCP', N'MCP', N'MasterCard® Purchasing Card®')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCS', N'MCS', N'Standard MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCT', N'MCT', N'Titanium MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCU', N'MCS', N'Unembossed MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCV', N'MCV', N'Merchant-Branded Program')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MCW', N'MCW', N'World MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDB', N'MDB', N'Debit MasterCard® BusinessCard Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDG', N'MDG', N'Gold Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDH', N'MDH', N'Debit Other Embossed MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDI', N'MDH', N'World Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDJ', N'MDJ', N'Debit MasterCard® (Enhanced)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDK', N'MDJ', N'Debit Other 2 Unembossed')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDL', N'MDL', N'Business Debit Other Embossed')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDM', N'MCF', N'Middle Market Fleet Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDN', N'MCP', N'Middle Market Purchasing Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDO', N'MDO', N'Debit Other')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDP', N'MDP', N'Platinum Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDQ', N'MCO', N'Middle Market Corporate Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDR', N'MDR', N'Debit Brokerage 27')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDS', N'MDS', N'Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDT', N'MDT', N'Commercial Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDU', N'MDS', N'Debit Unembossed MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MDW', N'MDW', N'MDW - (World Elite™ Debit MasterCard®)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MEB', N'MEB', N'MasterCard® Executive BusinessCard Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MEC', N'MEC', N'MasterCard® Electronic™ Commercial')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MED', N'MCE', N'Debit MasterCard® Electronic Card (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MEF', N'MEF', N'MasterCard® Electronic™ Payment Account')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MEO', N'MEO', N'MasterCard® Corporate Executive Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MEP', N'MDP', N'Premium Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MET', N'MDP', N'Titanium Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MFB', N'MFB', N'Flex World Elite')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MFD', N'MFD', N'Flex Platinum')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MFE', N'MFE', N'Flex Charge World Elite')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MFH', N'MFH', N'Flex World')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MFL', N'MFL', N'Flex Charge Platinum')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MFR', N'MPP', N'MasterCard® Commercial Reward Funding')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MFW', N'MFW', N'Flex Charge World')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MGF', N'MGF', N'MasterCard® Government Commercial Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MHA', N'MHA', N'MasterCard® Healthcare Prepaid Non-Tax')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MHB', N'MHB', N'MasterCard® HSA Substantiated')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MHC', N'MCC', N'MasterCard® Healthcare Credit Non-Substantiated')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MHH', N'MHH', N'MasterCard® HSA Non-Substantiated')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIA', N'MIA', N'Prepaid MasterCard® Unembossed Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIB', N'MCE', N'MasterCard® Electronic™ Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIC', N'MCS', N'MasterCard® Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MID', N'MDS', N'Debit Unembossed MasterCard® Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIG', N'MCS', N'Unembossed MasterCard® Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIH', N'MCE', N'Debit MasterCard® Electronic™ Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIJ', N'MCS', N'Debit MasterCard® Unembossed Non-U.S. Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIK', N'MRC', N'MasterCard® Electronic™ Prepaid Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIL', N'MRG', N'Prepaid Unembossed MasterCard® Student Card (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIP', N'MIP', N'MasterCard® Prepaid Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIS', N'MDS', N'Debit MasterCard® Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIU', N'MCS', N'Debit MasterCard® Unembossed (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MIU', N'MIU', N'Debit MasterCard® Unembossed (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MLA', N'MLA', N'MasterCard® Central Travel Solutions Air Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MLB', N'MLB', N'MLB - MasterCard Brazil Benefit for Home Improvement')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MLC', N'MCB', N'MasterCard® Micro-Business Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MLD', N'MLD', N'MasterCard Distribution Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MLE', N'MLE', N'MLE - MasterCard Brazil General Benefits')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MLF', N'MLF', N'MLF - (MasterCard Agro)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MLL', N'MLL', N'MasterCard® Central Travel Solutions Land Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MNF', N'MNF', N'MasterCard® Public Sector Commercial Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MNS', N'MCC', N'MasterCard® Non Standard')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MNW', N'MNW', N'MasterCard® World Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MOC', N'MOC', N'Standard Maestro® Social')
GO
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MOG', N'MOG', N'Maestro® Gold Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MOP', N'MOP', N'Maestro® Platinum')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MOW', N'MOW', N'World Maestro®')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPA', N'MPA', N'MasterCard® Prepaid Debit Standard - Payroll')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPB', N'MPB', N'MasterCard® Preferred Business Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPC', N'MCB', N'MasterCard® Professional Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPF', N'MPF', N'MasterCard® Prepaid Debit Standard - Gift')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPG', N'MPG', N'Debit MasterCard® Standard Prepaid - ')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPH', N'MPH', N'MasterCard® Cash')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPJ', N'MPJ', N'Prepaid MasterCard Debit Voucher Meal/Food Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPK', N'MPK', N'MasterCard® Prepaid Government Commercial Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPL', N'MPL', N'Platinum MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPM', N'MPM', N'MasterCard® Prepaid Debit Standard - Consumer Incentive')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPN', N'MPN', N'MasterCard® Prepaid Debit Standard - Insurance')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPO', N'MPO', N'MasterCard® Prepaid Debit Standard - Other')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPP', N'MPP', N'MasterCard® Prepaid Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPQ', N'MDS', N'MasterCard® Prepaid Debit Standard - Government Disaster Relief')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPR', N'MPR', N'MasterCard® Prepaid Debit Standard - Travel')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPT', N'MPT', N'MasterCard® Prepaid Debit Standard - Teen')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPV', N'MPV', N'MasterCard® Prepaid Debit Standard - Government')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPW', N'MPW', N'Debit MasterCard® BusinessCard Prepaid Workplace Business to Business')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPX', N'MPX', N'MasterCard® Prepaid Debit Standard - Flex Benefit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPY', N'MPY', N'MasterCard® Prepaid Debit Standard')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MPZ', N'MPZ', N'MasterCard® Prepaid Debit Standard - Government Consumer')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRB', N'MBE', N'MasterCard® Prepaid Electronic™ Business Card (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRC', N'MRC', N'Prepaid MasterCard® Electronic™ Card (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRF', N'MRF', N'Standard Deferred')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRG', N'MRG', N'MasterCard® Prepaid Card (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRH', N'MRH', N'MasterCard® Platinum Prepaid Travel Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRJ', N'MRJ', N'Prepaid MasterCard® Voucher Meal/Food Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRK', N'MRK', N'Prepaid MasterCard® Public Sector Commercial Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRL', N'MCE', N'Prepaid MasterCard Electronic Commercial Card (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRL', N'MRL', N'MasterCard Prepaid Business Preferred')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRO', N'MRO', N'MasterCard® Rewards Only')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRP', N'MRP', N'Standard Retailer Centric Payments')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRS', N'MRG', N'Prepaid MasterCard® Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MRW', N'MRW', N'Prepaid MasterCard® Business Card (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSA', N'MSA', N'Prepaid Maestro® Payroll Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSB', N'MSB', N'Maestro® Small Business Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSD', N'MCS', N'MasterCard Deferred Debit Consumer')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSF', N'MSF', N'Prepaid Maestro® Gift Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSG', N'MSG', N'Prepaid Maestro® Consumer Reloadable Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSI', N'MSI', N'Maestro® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSJ', N'MSJ', N'Maestro® Prepaid Voucher Meal and Food Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSM', N'MSM', N'Maestro® Prepaid Consumer Promotion Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSN', N'MSN', N'Maestro® Prepaid Insurance Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSO', N'MSO', N'Maestro® Prepaid Other Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSQ', N'MSQ', N'Reserved for Future Use')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSR', N'MSR', N'Prepaid Maestro® Travel Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSS', N'MSI', N'Maestro® Student Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MST', N'MST', N'Prepaid Maestro® Teen Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSV', N'MSV', N'Prepaid Maestro® Government Benefit Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSW', N'MSW', N'Prepaid Maestro® Corporate Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSX', N'MSX', N'Prepaid Maestro® Flex Benefit Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSY', N'MSY', N'Prepaid Maestro® Employee Incentive Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MSZ', N'MSZ', N'Prepaid Maestro® Emergency Assistance Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MTP', N'MTP', N'MasterCard® Platinum Prepaid Travel Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MUP', N'MDP', N'Premium Debit Unembossed MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MUS', N'MPG', N'Prepaid Unembossed MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MUW', N'MUW', N'MasterCard® World Domestic Affluent')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MWB', N'MWB', N'World MasterCard® for Business Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MWD', N'MWD', N'World Deferred')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MWE', N'MWE', N'World Elite MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MWO', N'MWO', N'World Elite MasterCard® Corporate Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MWR', N'MWR', N'World Retailer Centric Payments')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MXB', N'MCB', N'Debit Card X Code')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MXG', N'MDG', N'Gold Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MXO', N'MDO', N'Debit Card Other')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MXP', N'MDP', N'Platinum Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MXR', N'MDR', N'Debit Card Brokerage')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'MXS', N'MDS', N'Standard Debit MasterCard® Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'OLB', N'OLB', N'Maestro® Small Business - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'OLG', N'OLG', N'Maestro® Gold - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'OLI', N'OLS', N'Maestro® Student Card - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'OLP', N'OLP', N'Maestro® Platinum - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'OLS', N'OLS', N'Maestro® - Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'OLW', N'OLW', N'World Maestro® Delayed Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PMC', N'PMC', N'Proprietary Credit Card (Sweden domestic)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PMD', N'PMD', N'Proprietary Debit Card (Sweden domestic)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PSC', N'PSC', N'Common Proprietary Swedish Credit Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PSD', N'PSD', N'Common Proprietary Swedish Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVA', N'PVA', N'Private Label A')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVB', N'PVB', N'Private Label B')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVC', N'PVC', N'Private Label C')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVD', N'PVD', N'Private Label D')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVE', N'PVE', N'Private Label E')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVF', N'PVF', N'Private Label F')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVG', N'PVG', N'Private Label G')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVH', N'PVH', N'Private Label H')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVI', N'PVI', N'Private Label I')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVJ', N'PVJ', N'Private Label J')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'PVL', N'PVL', N'Private Label L')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'SAG', N'SAG', N'Gold MasterCard® Salary–Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'SAL', N'SAL', N'Standard Maestro® Salary')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'SAP', N'SAP', N'Platinum MasterCard® Salary–Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'SAS', N'SAS', N'Standard MasterCard® Salary–Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'SOS', N'SOS', N'Standard MasterCard® Social–Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'SUR', N'SUR', N'Prepaid Unembossed MasterCard® Card (Non-U.S.)')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TBE', N'TBE', N'MasterCard® Electronic™ Business - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCB', N'TCB', N'MasterCard® Executive Business Card - Immediate Debit')
GO
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCC', N'TCC', N'MasterCard® (mixed BIN) - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCE', N'TCE', N'MasterCard® Electronic™ - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCF', N'TCF', N'MasterCard® Fleet Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCG', N'TCG', N'Gold MasterCard® Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCO', N'TCO', N'MasterCard® Corporate - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCP', N'TCP', N'MasterCard® Purchasing Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCS', N'TCS', N'MasterCard® Standard Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TCW', N'TCW', N'World Signia MasterCard® Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TDN', N'TCP', N'Middle Market MasterCard® Purchasing Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TEB', N'TEB', N'MasterCard® Executive BusinessCard Card')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TEC', N'TEC', N'MasterCard® Electronic™ Commercial - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TEO', N'TEO', N'MasterCard® Corporate Executive Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TIB', N'TCE', N'MasterCard® Electronic™ Student Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TIC', N'TCS', N'MasterCard® Student Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TIU', N'TCS', N'MasterCard® Unembossed - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TLA', N'TCO', N'MasterCard® Central Travel Solutions Air  - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TNF', N'TNF', N'MasterCard® Public Sector Commercial Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TNW', N'TNW', N'MasterCard® New World - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TPB', N'TPB', N'MasterCard® Preferred Business Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TPC', N'TCB', N'MasterCard® Professional Card - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TPL', N'TPL', N'Platinum MasterCard® - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'TWB', N'TWB', N'World MasterCard® Black Edition - Immediate Debit')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'WBE', N'WBE', N'World MasterCard® Black Edition')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'WDR', N'MDH', N'World Debit MasterCard® Rewards')
INSERT [dbo].[MastercardProductType] ([LicensedProductId], [GCMSProductId], [ProductType]) VALUES (N'WMR', N'MCW', N'World MasterCard® Rewards')
