USE [ADMINISTRATION]
GO
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'A', N'Visa Traditional', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'AX', N'American Express', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'B', N'Visa Traditional Rewards', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'C', N'Visa Signature', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'D', N'Visa Signature Preferred', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'DI', N'Discover', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'DN', N'Diners', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'E', N'Proprietary ATM', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'F', N'Visa Classic', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'G', N'Visa Business', N'Business')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'G1', N'Visa Signature Business', N'Business')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'G3', N'Visa Business Enhanced', N'Business')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'G4', N'Visa Infinite Business', N'Business')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'I', N'Visa Infinite', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'I1', N'Visa Infinite Privilege', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'I2', N'Visa Ultra High Net Worth', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'J3', N'Visa Healthcare', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'JC', N'JCB', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'K', N'Visa Corporate T&E', N'Commercial')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'K1', N'Visa Government Corporate T&E', N'Government')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'L', N'Visa Electron', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'M', N'Mastercard', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'N', N'Visa Platinum', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'N1', N'Visa Rewards', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'N2', N'Visa Select', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'P', N'Visa Gold', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'Q', N'Private Label', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'Q2', N'Private Label Basic', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'Q3', N'Private Label Standard', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'Q4', N'Private Label Enhanced', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'Q5', N'Private Label Specialized', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'Q6', N'Private Label Premium', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'R', N'Proprietary', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'S', N'Visa Purchasing', N'Commercial')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'S1', N'Visa Purchasing with Fleet', N'Commercial')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'S2', N'Visa Government Purchasing', N'Government')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'S3', N'Visa Government Purchasing with Fleet', N'Government')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'S4', N'Visa Commercial Agriculture', N'Commercial')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'S5', N'Visa Commercial Transport', N'Commercial')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'S6', N'Visa Commercial Marketplace', N'Business')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'U', N'Visa Travel Money', N'Consumer')
INSERT [dbo].[VisaProductType] ([ProductId], [ProductType], [Type]) VALUES (N'V', N'Visa V Pay', N'Consumer')
