{
 "title": "Vault - Instrument Importer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "environment", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Gathering Customer Card Ids",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(vault_operation_duration_seconds{operation=\"get_instrument_ids\",component=\"prospector\",app=\"Vault.Instrument.Importer\",quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Instrument Import Time Per Batch",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(vault_operation_duration_seconds{operation=\"get_gw3_instruments\",component=\"importer\",app=\"Vault.Instrument.Importer\",quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Batch Message Time in SQS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(vault_batch_time_in_queue{resource=\"importer\",app=\"Vault.Instrument.Importer\",quantile=\"0.99\"})"
    }
   ]
  },
  { "title": "States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Migrations In Progress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vault_migrations_started{resource=\"prospector\",app=\"Vault.Instrument.Importer\"})"
    }
   ]
  },
  {
   "title": "Migration Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(vault_migration_errors{resource=\"prospector\",app=\"Vault.Instrument.Importer\"}[1m])) / sum(rate(vault_messages_handled_total{queue=\"vault-instrument-importer-local\",handler_type=\"CardInstrumentMigrationHandler\",handler_result=\"Handled\",app=\"Vault.Instrument.Importer\"}[1m]))) * 100"
    }
   ]
  },
  {
   "title": "Batches Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vault_operation_duration_seconds_count{operation=\"get_gw3_instruments\",component=\"importer\",app=\"Vault.Instrument.Importer\"})"
    }
   ]
  },
  {
   "title": "Batch Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(vault_migration_errors{resource=\"importer\",app=\"Vault.Instrument.Importer\"}[1m])) / sum(rate(vault_messages_handled_total{queue=\"vault-instrument-importer-local\",handler_type=\"CardInstrumentBatchFromGw3Handler\",handler_result=\"Handled\",app=\"Vault.Instrument.Importer\"}[1m]))) * 100"
    }
   ]
  },
  {
   "title": "Batches in Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vault_batches_enqueued{app=\"Vault.Instrument.Importer\"})"
    }
   ]
  },
  { "title": "Instruments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Instruments to Migrate ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(vault_instruments_to_migrate{app=\"Vault.Instrument.Importer\"})",
     "legendFormat": "Migration {{migrationId}}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "SQL Query Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"sql\", app=\"Vault.Instrument.Importer\", quantile=\"0.99\"}) by(resource, operation)",
     "legendFormat": "p99 {{resource}}({{operation}})"
    }
   ]
  },
  {
   "title": "SQL Query Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_io_duration_seconds_count{type=\"sql\", app=\"Vault.Instrument.Importer\"}[1m])) by (operation, resource)",
     "legendFormat": "{{resource}}({{operation}})"
    }
   ]
  },
  {
   "title": "DynamoDb Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"dynamodb\", app=\"Vault.Instrument.Importer\", quantile = \"0.99\"}) by (resource, operation)",
     "legendFormat": "p99 {{resource}}({{operation}})"
    }
   ]
  },
  {
   "title": "DynamoDb Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_io_duration_seconds_count{type=\"dynamodb\", app=\"Vault.Instrument.Importer\"}[1m])) by (operation, resource)",
     "legendFormat": "{{resource}}({{operation}})"
    }
   ]
  },
  {
   "title": "Cryptographic Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_hash_duration_seconds{app=\"Vault.Instrument.Importer\", quantile=\"0.99\"}) by(operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Cryptographic Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_hash_duration_seconds{app=\"Vault.Instrument.Importer\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "SQS Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"sqs\", app=\"Vault.Instrument.Importer\", quantile = \"0.99\"}) by (resource, operation)",
     "legendFormat": "p99 {{resource}}({{operation}})"
    }
   ]
  },
  {
   "title": "SQS Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_io_duration_seconds_count{type=\"sqs\", app=\"Vault.Instrument.Importer\"}[1m])) by (operation, resource)",
     "legendFormat": "{{resource}}({{operation}})"
    }
   ]
  },
  {
   "title": "KMS Encryption Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"kms\", app=\"Vault.Instrument.Importer\", quantile=\"0.99\"}) by(operation)",
     "legendFormat": "{{operation}} (p99)"
    }
   ]
  },
  {
   "title": "CLR stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open handles",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 86 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_open_handles{app=\"Vault.Instrument.Importer\"})",
       "legendFormat": "Handles"
      }
     ]
    },
    {
     "title": "Num threads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 86 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_num_threads{app=\"Vault.Instrument.Importer\"})",
       "legendFormat": "Handles"
      }
     ]
    },
    {
     "title": "Gc collections",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 86 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(dotnet_process_total_gc_collections{app=\"Vault.Instrument.Importer\"}[1m]))",
       "legendFormat": "Collections"
      }
     ]
    },
    {
     "title": "Total memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 86 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_total_memory_bytes{app=\"Vault.Instrument.Importer\"})",
       "legendFormat": "Collections"
      }
     ]
    },
    {
     "title": "Working set",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 86 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_working_set_bytes{app=\"Vault.Instrument.Importer\"})",
       "legendFormat": "Handles"
      }
     ]
    },
    {
     "title": "Virtual memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 86 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_virtual_memory_bytes{app=\"Vault.Instrument.Importer\"})",
       "legendFormat": "Handles"
      }
     ]
    }
   ]
  },
  {
   "title": "CLR Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(dotnet_process_num_threads{app=\"Vault.Instrument.Importer\"})",
       "legendFormat": "max(threads)"
      }
     ]
    },
    {
     "title": "Open handles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(dotnet_process_open_handles{app=\"Vault.Instrument.Importer\"})",
       "legendFormat": "max(handles)"
      }
     ]
    },
    {
     "title": "Gc collections per generation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(dotnet_process_total_gc_collections{app=\"Vault.Instrument.Importer\"}[1m])) by (gen)",
       "legendFormat": "gen{{gen}}"
      }
     ]
    },
    {
     "title": "Max memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(dotnet_process_total_memory_bytes{app=\"Vault.Instrument.Importer\"})",
       "legendFormat": "max mem usage"
      }
     ]
    }
   ]
  }
 ]
}