{
 "title": "Vault - Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vault API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_errors_total{app=\"Vault.Api\"}[1m])) / (sum(rate(vault_http_requests_total{app=\"Vault.Api\"}[1m])) + sum(rate(vault_errors_total{app=\"Vault.Api\"}[1m])))"
    }
   ]
  },
  {
   "title": "External API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_errors_total{app=\"Vault.External.Api\"}[1m])) / (sum(rate(vault_http_requests_total{app=\"Vault.External.Api\"}[1m])) + sum(rate(vault_errors_total{app=\"Vault.External.Api\"}[1m])))"
    }
   ]
  },
  {
   "title": "Account Configuration API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_errors_total{app=\"Vault.AccountConfiguration.Api\"}[1m])) / (sum(rate(vault_http_requests_total{app=\"Vault.AccountConfiguration.Api\"}[1m])) + sum(rate(vault_errors_total{app=\"Vault.AccountConfiguration.Api\"}[1m])))"
    }
   ]
  },
  { "title": "Account Configuration API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Onboard Account RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_http_resource_duration_seconds_count{resource=\"onboard_vault_account\", app=\"Vault.AccountConfiguration.Api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Onboard Account Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{resource=\"onboard_vault_account\", quantile=\"0.99\", app=\"Vault.AccountConfiguration.Api\"})"
    }
   ]
  },
  {
   "title": "Retrieve Account RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_http_resource_duration_seconds_count{resource=~\"retrieve_vault_account|retrieve_vault_account_by_client_id\", app=\"Vault.AccountConfiguration.Api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Retrieve Account Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{resource=~\"retrieve_vault_account|retrieve_vault_account_by_client_id\", quantile=\"0.99\", app=\"Vault.AccountConfiguration.Api\"})"
    }
   ]
  },
  { "title": "External API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Stored Token RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_http_resource_duration_seconds_count{resource=\"store_token\", app=\"Vault.External.Api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Stored Token Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{resource=\"store_token\", quantile=\"0.99\", app=\"Vault.External.Api\"})"
    }
   ]
  },
  {
   "title": "Stored Instrument RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_http_resource_duration_seconds_count{resource=\"store_instrument\", app=\"Vault.External.Api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Stored Instrument Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{resource=\"store_instrument\", quantile=\"0.99\", app=\"Vault.External.Api\"})"
    }
   ]
  },
  { "title": "Cards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Retrieve RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_http_resource_duration_seconds_count{resource=\"get_card_details\", app=\"Vault.Api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Retrieve Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{resource=\"get_card_details\", quantile=\"0.99\", app=\"Vault.Api\"})"
    }
   ]
  },
  { "title": "Instruments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Store RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_http_resource_duration_seconds_count{resource=\"store_instrument\", app=\"Vault.Api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Store Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{resource=\"store_instrument\", quantile=\"0.99\", app=\"Vault.Api\"})"
    }
   ]
  },
  {
   "title": "Retrieve RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_http_resource_duration_seconds_count{resource=\"retrieve_instrument\", app=\"Vault.Api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Retrieve Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{resource=\"retrieve_instrument\", quantile=\"0.99\", app=\"Vault.Api\"})"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Vault API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "External API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.External.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Account Configuration API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.AccountConfiguration.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "DynamoDb Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"dynamodb\", quantile = \"0.99\"}) by (resource, operation)",
     "legendFormat": "p99 {{operation}}"
    }
   ]
  },
  {
   "title": "DynamoDb Operations Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_io_duration_seconds_count{type=\"dynamodb\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Cryptographic Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_hash_duration_seconds{quantile = \"0.99\"}) by (operation)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "avg(vault_io_duration_seconds{quantile = \"0.99\", type=\"kms\"}) by (type, resource)",
     "legendFormat": "{{type}} ({{resource}})"
    }
   ]
  },
  {
   "title": "Cryptographic Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_hash_duration_seconds{}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(rate(vault_io_duration_seconds_count{type=\"kms\"}[1m])) by (type, resource)",
     "legendFormat": "{{type}} ({{resource}})"
    }
   ]
  },
  {
   "title": "Sql Query Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"sql\", quantile = \"0.99\"}) by (resource, operation)",
     "legendFormat": "p99 {{resource}} ({{operation}})"
    }
   ]
  },
  {
   "title": "Sql Query Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_io_duration_seconds_count{type=\"sql\"}[1m])) by (operation, resource)",
     "legendFormat": "{{resource}}({{operation}})"
    }
   ]
  },
  { "title": "Downstream Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "FXP Validation API Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",resource=\"fxp\",operation=\"validate_bank_account\",quantile=\"0.95\"})",
     "legendFormat": "95th Perc"
    },
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",resource=\"fxp\",operation=\"validate_bank_account\",quantile=\"0.99\"})",
     "legendFormat": "99th Perc"
    }
   ]
  },
  {
   "title": "FXP Validation API HTTP Response Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(increase(vault_fxp_http_status_code_count[1m]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum (increase(vault_fxp_http_status_code_count[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Digital Wallets Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",operation=\"decrypt_digital_wallet\",quantile=\"0.95\"}) by (resource)",
     "legendFormat": "p95 {{resource}}"
    },
    {
     "expr": " avg(vault_io_duration_seconds{type=\"http\",operation=\"decrypt_digital_wallet\",quantile=\"0.99\"}) by (resource)",
     "legendFormat": "p99 {{resource}}"
    }
   ]
  },
  {
   "title": "Digital Wallets HTTP Response Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(increase(vault_applepay_http_status_code_count[1m]))",
     "legendFormat": "applepay {{status}}"
    },
    {
     "expr": "sum (increase(vault_applepay_http_status_code_count[1m]))",
     "legendFormat": "applepay Total"
    },
    {
     "expr": "sum by (status)(increase(vault_googlepay_http_status_code_count[1m]))",
     "legendFormat": "googlepay {{status}}"
    },
    {
     "expr": "sum (increase(vault_googlepay_http_status_code_count[1m]))",
     "legendFormat": "googlepay Total"
    }
   ]
  },
  { "title": "Alerts - Sandbox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Vault API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Account Configuration API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.AccountConfiguration.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "External API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.External.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Sql Query Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"sql\", quantile = \"0.99\"}) by (resource, operation)",
     "legendFormat": "p99 {{resource}} ({{operation}})"
    }
   ]
  },
  {
   "title": "DynamoDb Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"dynamodb\", quantile = \"0.99\"}) by (resource, operation)",
     "legendFormat": "p99 {{operation}}"
    }
   ]
  },
  {
   "title": "Cryptographic Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_hash_duration_seconds{quantile = \"0.99\"}) by (operation)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "avg(vault_io_duration_seconds{quantile = \"0.99\", type=\"kms\"}) by (type, resource)",
     "legendFormat": "{{type}} ({{resource}})"
    }
   ]
  },
  {
   "title": "FXP Validation API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",resource=\"fxp\",operation=\"validate_bank_account\",quantile=\"0.95\"})",
     "legendFormat": "95th Perc"
    },
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",resource=\"fxp\",operation=\"validate_bank_account\",quantile=\"0.99\"})",
     "legendFormat": "99th Perc"
    }
   ]
  },
  {
   "title": "Digital Wallets Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",operation=\"decrypt_digital_wallet\",quantile=\"0.95\"}) by (resource)",
     "legendFormat": "p95 {{resource}}"
    },
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",operation=\"decrypt_digital_wallet\",quantile=\"0.99\"}) by (resource)",
     "legendFormat": "p99 {{resource}}"
    }
   ]
  },
  { "title": "Alerts - Prod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Vault API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Account Configuration API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.AccountConfiguration.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "External API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"Vault.External.Api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Sql Query Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"sql\", quantile = \"0.99\"}) by (resource, operation)",
     "legendFormat": "p99 {{resource}} ({{operation}})"
    }
   ]
  },
  {
   "title": "DynamoDb Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"dynamodb\", quantile = \"0.99\"}) by (resource, operation)",
     "legendFormat": "p99 {{operation}}"
    }
   ]
  },
  {
   "title": "Cryptographic Operations Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 99 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_hash_duration_seconds{quantile = \"0.99\"}) by (operation)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "avg(vault_io_duration_seconds{quantile = \"0.99\", type=\"kms\"}) by (type, resource)",
     "legendFormat": "{{type}} ({{resource}})"
    }
   ]
  },
  {
   "title": "FXP Validation API Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",resource=\"fxp\",operation=\"validate_bank_account\",quantile=\"0.95\"})",
     "legendFormat": "95th Perc"
    },
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",resource=\"fxp\",operation=\"validate_bank_account\",quantile=\"0.99\"})",
     "legendFormat": "99th Perc"
    }
   ]
  },
  {
   "title": "Digital Wallets Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 99 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",operation=\"decrypt_digital_wallet\",quantile=\"0.95\"}) by (resource)",
     "legendFormat": "p95 {{resource}}"
    },
    {
     "expr": "avg(vault_io_duration_seconds{type=\"http\",operation=\"decrypt_digital_wallet\",quantile=\"0.99\"}) by (resource)",
     "legendFormat": "p99 {{resource}}"
    }
   ]
  }
 ]
}