{
 "title": "Vault - APIs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "api", "query": "label_values(app)" },
   { "name": "environment", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_http_resource_duration_seconds_count{app=\"$api\"}[1m])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Response Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vault_http_resource_duration_seconds_count{app=\"$api\"}[1m])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"$api\", quantile = \"0.95\"}) by (resource)",
     "legendFormat": "95th perc({{resource}})"
    },
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"$api\", quantile = \"0.99\"}) by (resource)",
     "legendFormat": "99th perc({{resource}})"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(vault_errors_total{app=\"$api\"}[1m])) / (sum(rate(vault_http_requests_total{app=\"$api\"}[1m])) + sum(rate(vault_errors_total{app=\"$api\"}[1m])))"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"$api\", quantile=\"0.99\"})"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_http_requests_total{ app=\"$api\" }[1m]))",
     "legendFormat": "{{rps}}"
    }
   ]
  },
  {
   "title": "HTTP Response Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(rate(vault_http_requests_total{app=\"$api\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"$api\", quantile = \"0.95\"})",
     "legendFormat": "95th Perc"
    },
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"$api\", quantile = \"0.99\"})",
     "legendFormat": "99th Perc"
    },
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"$api\", quantile = \"0.75\"})",
     "legendFormat": "75th Perc"
    },
    {
     "expr": "avg(vault_http_resource_duration_seconds{app=\"$api\", quantile = \"0.50\"})",
     "legendFormat": "50th Perc"
    }
   ]
  },
  {
   "title": "CLR stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open handles",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_open_handles{app=\"$api\"})",
       "legendFormat": "Handles"
      }
     ]
    },
    {
     "title": "Num threads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_num_threads{app=\"$api\"})",
       "legendFormat": "Handles"
      }
     ]
    },
    {
     "title": "Gc collections",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(dotnet_process_total_gc_collections{app=\"$api\"}[1m]))",
       "legendFormat": "Collections"
      }
     ]
    },
    {
     "title": "Total memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 35 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_total_memory_bytes{app=\"$api\"})",
       "legendFormat": "Handles"
      }
     ]
    },
    {
     "title": "Working set",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 35 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_working_set_bytes{app=\"$api\"})",
       "legendFormat": "Handles"
      }
     ]
    },
    {
     "title": "Virtual memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 35 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(dotnet_process_virtual_memory_bytes{app=\"$api\"})",
       "legendFormat": "Handles"
      }
     ]
    }
   ]
  },
  {
   "title": "CLR Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(dotnet_process_num_threads{app=\"$api\"})",
       "legendFormat": "max(threads)"
      }
     ]
    },
    {
     "title": "Open handles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(dotnet_process_open_handles{app=\"$api\"})",
       "legendFormat": "max(handles)"
      }
     ]
    },
    {
     "title": "Gc collections per generation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(dotnet_process_total_gc_collections{app=\"$api\"}[1m])) by (gen)",
       "legendFormat": "gen{{gen}}"
      }
     ]
    },
    {
     "title": "Max memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(dotnet_process_total_memory_bytes{app=\"$api\"})",
       "legendFormat": "max mem usage"
      }
     ]
    }
   ]
  }
 ]
}